# run: conda env create -n <name> --file environment.yml
#conda env update --file environment.yml  --prune 
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.0
  - nvidia::cudatoolkit=11.7
  - conda-forge::transformers=4.28.1
  - conda-forge::datasets=2.12.0
  - pandas=2.0.1
  - anaconda::scikit-learn=1.2.0
  - conda-forge::matplotlib=3.7.1
  - conda-forge::accelerate
  - black=23.3.0
  - isort=5.12.0
  - conda-forge::hydra-core=1.3.2
  - pip
  - pip:
  