# run: conda env create -n <name> --file environment.yml
#conda env update --file environment.yml  --prune 
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.0
  - nvidia::cudatoolkit=11.7
  - conda-forge::transformers 
  - conda-forge::datasets
  - anaconda::pandas 
  - anaconda::scikit-learn
  - conda-forge::matplotlib
  - conda-forge::accelerate
  - black
  - isort
  - conda-forge::hydra-core
  - pip
  - pip:
  