defaults:
  - dataset: de
  - task: ???
#wandb args  
use_wandb: True
project_name: huggingface 
run_name: None
group_name: None
# Training Arguments
batch_size: 4
evaluation_strategy: "epoch"
save_strategy: "epoch"
learning_rate: 1.477e-05
num_train_epochs: 20
weight_decay: 0.089
load_best_model_at_end: True
metric_for_best_model: micro avg.f1-score
save_total_limit: 2
fp16: True
label_smoothing_factor: 0.0


# Inference
threshold: 0.4

# Dataset
upsample: False
downsample: False

# Dataset
augmentation:
  use: False
  generated_classes_indices: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
  generated_samples_path: /dhc/groups/appl_ml_ss23_1/datasets/generated/generated_tweets

add_translated : False

delete: True  

# Hydra
hydra:
  run:
    dir: /dhc/groups/appl_ml_ss23_1/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

deterministic: False