# @package _group_
name : "infer"
text : "Ich nehme seit einer Woche Aspirin und seitdem ist mir dauernd übel"
checkpoint_path : "/dhc/home/smilla.fox/MedNLP/output/checkpoints/230514_14:46:28/checkpoint-797"