# @package _group_
name : "output"

model_path : /dhc/groups/appl_ml_ss23_1/hydra_outputs/2023-07-13/23-40-40/checkpoint-1408
output_path : /dhc/groups/appl_ml_ss23_1/output/de/output.csv
dataset_path : /dhc/groups/appl_ml_ss23_1/testdata/de/ntcir17_mednlp-sc_sm_de_test.csv